before_script:
    - ruby -v
    - which ruby
    - gem install bundler --no-ri --no-rdoc
    - bundle install

stages:
    - deploy

deploy to nolimit:
    stage: deploy
    script: bundle exec cap nolimit deploy
    environment: nolimit