settings:
    doctrine:
        meta:
            entity_path:
                - 'src/Ovs/Bovimarket/Entity/'
            auto_generate_proxies: false
            proxy_dir: "cache/proxies"
            cache: ~
        connection:
            driver: "pdo_mysql"
            host: 'localhost'
            dbname: 'bovimarket_preprod'
            user: bv_preprod
            password: TadBasht
    session:
        lifetime: 3600
    debug: true
    api:
        oauthLogin: "mobile"
        oauthSecret: "7d5cc9b6-1ed8-49e0-a56a-ecfb0a2f5f69"
        baseURI: "http://185.30.92.167:8081/bovimarket/api/"
        token: "1e8aed3e-9b5e-4c22-8971-dd3b57b5b6ba"
        #baseURI: "http://51.254.44.168:8080/bovimarket/api/"
        #token: "52a453ac-70e0-43ee-a59d-9af10eed4a9f"
    displayErrorDetails: true
    logger:
        name: "slim-app"
        path: "app.log"