map.homepage:
    action: "Ovs\\Bovimarket\\Controller\\MapController:index"
    path: "/"

flash.qrcode:
    action: "Ovs\\Bovimarket\\Controller\\FlashController:qrCode"
    path: "/qrcode"


flash.recettes_list:
    action: "Ovs\\Bovimarket\\Controller\\FlashController:recettes"
    path: "/viande/{categ}/{idMorceau}/recettes"

flash.recettes_detail:
    action: "Ovs\\Bovimarket\\Controller\\FlashController:detailRecette"
    path: "/viande/{categ}/{idMorceau}/recette/{idRecette}"

flash.morceau:
    action: "Ovs\\Bovimarket\\Controller\\FlashController:detailMorceau"
    path: "/viande/{categ}/morceau/{idMorceau}"

flash.cuissons_list:
    action: "Ovs\\Bovimarket\\Controller\\FlashController:cuissonsList"
    path: "/viande/{categ}/{idMorceau}/cuissons"

flash.cuissons_detail:
    action: "Ovs\\Bovimarket\\Controller\\FlashController:detailCuisson"
    path: "/viande/{categ}/{idMorceau}/cuissons/{idCuisson}"

flash.categorie:
    action: "Ovs\\Bovimarket\\Controller\\FlashController:categorieViande"
    path: "/viande/{categ}/{id}[/{idProducteur}]"

app.billets.list:
    action: "Ovs\\Bovimarket\\Controller\\BilletsController:list"
    path: "/news"

app.entite.detail_region:
    action: "Ovs\\Bovimarket\\Controller\\EntiteController:showDetailRegion"
    path: "/entite/region"

app.entite.detail:
    action: "Ovs\\Bovimarket\\Controller\\EntiteController:showDetail"
    path: "/entite/{id}"
    
app.entite.menu:
    action: "Ovs\\Bovimarket\\Controller\\EntiteController:getMenu"
    path: "/menu/{id}/{date}"


app.entite.search_map:
    action: "Ovs\\Bovimarket\\Controller\\EntiteController:searchMap"
    path: "/search_zone"

app.entite.search_form:
    action: "Ovs\\Bovimarket\\Controller\\EntiteController:search"
    path: "/search"
    methods:
        - "GET"
        - "POST"

app.entite.do_search:
    action: "Ovs\\Bovimarket\\Controller\\EntiteController:doSearch"
    path: "/results"
    methods:
        - "GET"
        - "POST"

app.entite.get_certif:
    action: "Ovs\\Bovimarket\\Controller\\EntiteController:getCertifications"
    path: "/certifications/[{viande}]"

app.entite.produits:
    action: "Ovs\\Bovimarket\\Controller\\ProduitController:listProduits"
    path: "/produits/{id}"

app.entite.add_to_cart:
    action: "Ovs\\Bovimarket\\Controller\\ProduitController:addToCart"
    path: "/produits/{idEntite}/addToCart/{idProduit}"

app.entite.del_to_cart:
    action: "Ovs\\Bovimarket\\Controller\\ProduitController:delToCart"
    path: "/produits/{idEntite}/delToCart/{idProduit}"

app.entite.reserve_table:
    action: "Ovs\\Bovimarket\\Controller\\EntiteController:reserverTable"
    path: "/entite/{idEntite}/reserver"

app.entite.process_reserve_table:
    action: "Ovs\\Bovimarket\\Controller\\EntiteController:doReserverTable"
    path: "/entite/{idEntite}/reserver/process"

app.entite.reservation_success:
    action: "Ovs\\Bovimarket\\Controller\\EntiteController:reservationSuccess"
    path: "/entite/reservation/success"


app.commande.show_cart:
    action: "Ovs\\Bovimarket\\Controller\\ProduitController:showCart"
    path: "/panier"

app.commande.remove_from_cart:
    action: "Ovs\\Bovimarket\\Controller\\ProduitController:removeFromCart"
    path: "/panier/remove/{idProduit}"

app.commande.select_livraison:
    action: "Ovs\\Bovimarket\\Controller\\ConsoController:selectLivraison"
    path: "/panier/delivery"

app.commande.save_livraison:
    action: "Ovs\\Bovimarket\\Controller\\ConsoController:saveCanal"
    path: "/panier/delivery/save"
    methods:
        - "POST"

app.commande.select_paiement:
    action: "Ovs\\Bovimarket\\Controller\\ConsoController:choixPaiement"
    path: "/panier/paiement"

app.commande.save_paiement:
    action: "Ovs\\Bovimarket\\Controller\\ConsoController:savePaiement"
    path: "/panier/paiement/save"
    methods:
        - "POST"

app.commande.do_paiement:
    action: "Ovs\\Bovimarket\\Controller\\ConsoController:doPaiement"
    path: "/panier/paiement/process"

app.commande.save_commande:
    action: "Ovs\\Bovimarket\\Controller\\ConsoController:saveCommande"
    path: "/panier/commande/save"

app.login.form:
    action: "Ovs\\Bovimarket\\Controller\\UserController:loginForm"
    path: "/login"

app.login.login:
    action: "Ovs\\Bovimarket\\Controller\\UserController:login"
    path: "/login/process"
    methods:
        - "POST"

app.login.register:
    action: "Ovs\\Bovimarket\\Controller\\UserController:register"
    path: "/register/process"
    methods:
        - "POST"

app.not_connected:
    action: "Ovs\\Bovimarket\\Controller\\UserController:notConnected"
    path: "/presentation"

app.register.form:
    action: "Ovs\\Bovimarket\\Controller\\UserController:registerForm"
    path: "/register"

app.logout:
    action: "Ovs\\Bovimarket\\Controller\\UserController:logout"
    path: "/logout"

app.profile:
    action: "Ovs\\Bovimarket\\Controller\\UserController:profile"
    path: "/profile"
    methods:
        - "GET"
        
app.user.profile:
   action: "Ovs\\Bovimarket\\Controller\\UserController:showProfile"
   path: "/user/{idUser}"
   methods:
       - "GET"       

app.update_profile:
    action: "Ovs\\Bovimarket\\Controller\\UserController:updateProfile"
    path: "/profile/update"
    methods:
        - "POST"
        
app.user.favoris:
    action: "Ovs\\Bovimarket\\Controller\\UserController:favoris"
    path: "/profile/favoris"
    
app.user.friends:
    action: "Ovs\\Bovimarket\\Controller\\UserController:friends"
    path: "/profile/amis"

app.commande.list:
    action: "Ovs\\Bovimarket\\Controller\\ConsoController:listCommandes"
    path: "/commandes"
    
app.commande.recup:
    action: "Ovs\\Bovimarket\\Controller\\ConsoController:recupCommandes"
    path: "/commandes/recuperation"

app.commande.detail:
    action: "Ovs\\Bovimarket\\Controller\\ConsoController:showCommande"
    path: "/commande/{id}"

app.change.favorite:
    action: "Ovs\\Bovimarket\\Controller\\UserController:changeFavorite"
    path: "/favorite/{idEntite}/{action}"