<?php

namespace Ovs\Bovimarket\Entity;

/**
 * RecetteFavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteFavorisRepository extends \Doctrine\ORM\EntityRepository
{
	public function findForUser($user) {
		if(!is_numeric($user)){
			$user = $user->getId();
		}

		return $this->findBy(array("userId"=>$user));
	}
}
